server:
  servlet:
    context-path: /ApprovalAssistant

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ApprovalAssistant?serverTimezone=Asia/Shanghai
    username: root
    password: jjjj5299
#    driverClassName: org.h2.Driver
#    username: root
#    password: 123456
#    platform: h2
#    url: jdbc:h2:mem:jwt-demo
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true